"""unique course

Revision ID: 0f4d88df9b93
Revises: 6ac0aef4b6bc
Create Date: 2018-12-19 14:09:24.798346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4d88df9b93'
down_revision = '6ac0aef4b6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_course', 'courses', ['title', 'teacher'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_course', 'courses', type_='unique')
    # ### end Alembic commands ###
