"""many to many

Revision ID: 36255b5ce9c3
Revises: 
Create Date: 2018-12-14 12:52:19.687803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36255b5ce9c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'class_id')
    )
    op.drop_constraint('courses_ibfk_1', 'courses', type_='foreignkey')
    op.drop_column('courses', 'class_entity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('class_entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_ibfk_1', 'courses', 'classes', ['class_entity_id'], ['id'])
    op.drop_table('class_course')
    # ### end Alembic commands ###
