"""postgres

Revision ID: 6ac0aef4b6bc
Revises: 
Create Date: 2018-12-17 10:45:44.327101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac0aef4b6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('semasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('teacher', sa.String(length=12), nullable=False),
    sa.Column('students_num', sa.Integer(), nullable=False),
    sa.Column('semaster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semaster_id'], ['semasters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'class_id')
    )
    op.create_table('time_serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('start_week', sa.Integer(), nullable=False),
    sa.Column('end_week', sa.Integer(), nullable=False),
    sa.Column('start_class', sa.Integer(), nullable=False),
    sa.Column('end_class', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_serials')
    op.drop_table('class_course')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('semasters')
    op.drop_table('classes')
    # ### end Alembic commands ###
