"""modified database

Revision ID: 6f872ddde5cd
Revises: 36255b5ce9c3
Create Date: 2018-12-14 14:04:50.459029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f872ddde5cd'
down_revision = '36255b5ce9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('semaster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'semasters', ['semaster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'semaster_id')
    # ### end Alembic commands ###
