"""test

Revision ID: fe8e378eecd4
Revises: a474ba1b297a
Create Date: 2018-12-14 14:22:07.072610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8e378eecd4'
down_revision = 'a474ba1b297a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_serials', sa.Column('test_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_serials', 'test_field')
    # ### end Alembic commands ###
